### ISSUE TITLE
script takes input of folder location to clean

### ISSUE THREAD

**Issue by skcy2001** [prashantsengar/CleanPy#20]
User can specify which folder to clean by mentioning its path in config.ini

Eg.
Config.ini:
`PLocation: "C:/xyz/folderlocation"`

**Comment by prashantsengar** [comment]
Cool idea @skcy2001 🆒
I wanted to add this feature in it.

While you are at it, can you also:
1. add the extension options in the config file too? It is currently a dictionary in the script. Instead of this, we can have the script read this from the config file so that the users can change those. 
2. Take the input folder as a command line argument.
Eg. python arrange.py /PATH/TO/CLEAN
If no path is specified, clean the current directory.

If you can do this, please let me know :) 💯

**Comment by skcy2001** [comment]
Yep, I will do it.

**Comment by skcy2001** [comment]
Check #10 . Did all the changes you mentioned.
